# Generated by Django 5.1.2 on 2024-10-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='expiration_code',
            new_name='expiration_date',
        ),
    ]
